apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-data
spec:
  storageClassName: sdf-group-rubin
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restore
  template:
    metadata:
      labels:
        app: restore
    spec:
      containers:
#      - name: mongo-restore
#        image: mongo:bionic
#        command: [ "bash", "-c", "sleep infinity" ]
#        volumeMounts:
#        - mountPath: /data
#          name: mongo-restore
      - name: postgres
        image: postgres:14-alpine
        command:  [ "bash", "-c", "sleep infinity" ]
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /source
          name: source
      - name: scp
        image: kroniak/ssh-client
        command:  [ "bash", "-c", "sleep infinity" ]
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /source
          name: source
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: restore-data
      - name: source
        persistentVolumeClaim:
          claimName: source-data


