
resources:
- ns.yaml
# cnpg
- cnpg-panda-server-database.yaml
- cnpg-panda-server-pooler.yaml

### hmm... the endpoint doens't exist here for kustomize to do anythign abot it; add into Makefile?
#patchesStrategicMerge:
#- endpoints-patch.yaml

secretGenerator:
- name: usdf-panda-server-creds
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/username
  - etc/.secrets/password

#nameSuffix: -dev
namespace: panda-db
commonLabels:
  env: prod
  app: panda-server
  namespace: panda-db

#configMapGenerator:
#- name: telegraf-postgres
#  files:
#  - telegraf.conf
#  - postgresql_custom_data.conf 

